# GN3 API Configurations on CD

## Tags

* assigned: alexm, Bonfacem
* keywords: configurations, CD, API, genenetwork3
* type: bug
* priority: high

## Description

The issue is that there is no straightforward way of knowing how to call the GN3 API from GN2. Multiple configurations, such as GN_SERVER_URL and GN3_LOCAL_URL, exist, making it difficult to understand how to debug.

The `GN_SERVER_URL` which from  config is running on port 8880 results into this error:

```
"HTTPConnectionPool(host='localhost', port=8880): Max retries exceeded with URL: /api/llm/gnqna (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd45a8d5a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
```
